import User from '../assets/img/product-page/up-pool-img1.png';

export const launchpads_data = [
    {
        user: User,
        project_title: "Project name",
        project_desc: "Example text here 2",
        project_header_bused: "1 BUSD = 4 XY",
        total_raise_title: "Total Raise",
        total_raise_point: "237497.44",
        maximum_completed_pool_title: "Maximum",
        maximum_completed_pool_point: "1939.85",
        access_title: "Access",
        access_ans: "Public",
        progress: "50%",
        max_participants_points: "9499897.78/9500000",
    },
    {
        user: User,
        project_title: "Project name",
        project_desc: "Example text here 2",
        project_header_bused: "1 BUSD = 4 XY",
        total_raise_title: "Total Raise",
        total_raise_point: "237497.44",
        maximum_completed_pool_title: "Maximum",
        maximum_completed_pool_point: "1939.85",
        access_title: "Access",
        access_ans: "Public",
        progress: "50%",
        max_participants_points: "9499897.78/9500000",
    },
    {
        user: User,
        project_title: "Project name",
        project_desc: "Example text here 2",
        project_header_bused: "1 BUSD = 4 XY",
        total_raise_title: "Total Raise",
        total_raise_point: "237497.44",
        maximum_completed_pool_title: "Maximum",
        maximum_completed_pool_point: "1939.85",
        access_title: "Access",
        access_ans: "Public",
        progress: "50%",
        max_participants_points: "9499897.78/9500000",
    },
    {
        user: User,
        project_title: "Project name",
        project_desc: "Example text here 2",
        project_header_bused: "1 BUSD = 4 XY",
        total_raise_title: "Total Raise",
        total_raise_point: "237497.44",
        maximum_completed_pool_title: "Maximum",
        maximum_completed_pool_point: "1939.85",
        access_title: "Access",
        access_ans: "Public",
        progress: "50%",
        max_participants_points: "9499897.78/9500000",
    },
    
]